TechLadies/highpoint

Gemfile
Gemfile.lock
README.md
spec/rails_helper.rb
spec/spec_helper.rb

This change adds the following libraries to the test environment:
- RSpec for writing and running tests
- FactoryGirl for fixtures
- ShouldaMatchers for testing the ActiveModel DSL
---
---

Add testing frameworks

---

.rspec
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/clearance.rb
db/migrate/20160929164755_create_clearance_users.rb
db/schema.rb
db/seeds.rb
db/seeds/users.rb
spec/controllers/donors_controller_spec.rb
spec/factories/clearance.rb
spec/rails_helper.rb

This change allows a user (admin) to login. The screenshots of the donor page are below:
I have made the changes requested from my previous pull request.

Allow admin users to sign in

---

app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/users/_form.html.erb
config/initializers/clearance.rb
config/locales/clearance.en.yml

This change allows users to sign out of the management system.
The 'sign out' function is under the user modal drop-down button
After the user signs out, it leads them back to the login page

Allow users to sign out

---

app/models/donor.rb
app/views/donors/index.html.erb
spec/models/donor_spec.rb

This enhancement makes NRIC/UEN searchable in DonorsController#index.
---
---

[Fix #54] Allow user to search for donor by NRIC/UEN

---

app/controllers/events_controller.rb
app/views/events/_index.html.erb
app/views/events/_new.html.erb
app/views/events/create.js.erb
app/views/events/index.html.erb
app/views/events/index.js.erb

This change allows Users to see errors in the `event` modal.
Is also adds an alert message to the `events/index` page on successful `event` creation.
---
---
---
---

[Fix #27] Add client side validation to Event modal

---

app/controllers/users_controller.rb
app/views/layouts/_navbar.html.slim
app/views/users/show.html.slim
config/routes.rb
spec/routing/users_routing_spec.rb

This change creates a `users/show` page which can be accessed by clicking on "My Profile" link in the dropdown in the navbar. 
This change also makes `donations/index` a root page.
---
---
---
---

This change adds a Profile page for a User

---

app/controllers/events_controller.rb
app/finders/events_finder.rb
spec/finders/events_finder_spec.rb

This change creates a class `EventsFinder` which is responsible for search and sort of Events.
---
---

Move EventsController#index logic into a separate class

---

app/controllers/application_controller.rb
app/controllers/donors_controller.rb
app/controllers/events_controller.rb
app/finders/donors_finder.rb
app/models/donor.rb
app/views/donors/index.html.slim
spec/factories/donors.rb
spec/finders/donors_finder_spec.rb

This change creates a class `DonorsFinder` which is responsible for search, filter and sort of Donors.
---
--- 

Move DonationsController#index logic in a separate class

---

.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/clearance/passwords_controller.rb
app/models/cause.rb
app/models/donation.rb
app/models/donor.rb
app/models/event.rb
app/views/passwords/create.html.slim
app/views/passwords/edit.html.slim
app/views/passwords/new.html.slim
app/views/sessions/new.html.slim
config/environments/development.rb
config/environments/production.rb
config/initializers/clearance.rb

This change allows Users to reset their passwords by clicking on "Forgot Password?" on "Sign Up" page. See the screenshots below.
Please note, that to test the feature locally, **you need to install** `mailcatcher`:
1. `gem install mailcatcher`
2. `mailcatcher`
3. Go to http://localhost:1080/
For the feature to work on Heroku, @Drenmi please add an "SGAPIKEY" environment variable in Heroku:
`$ heroku config:add SGAPIKEY=our_api_key` 
---
If the entered email is not in the DB:
If entered email is correct:
---
---
[1]: …

Allow Users reset paswords

---

app/controllers/reports_controller.rb
app/helpers/reports_helper.rb
app/models/donation.rb
app/models/report.rb
app/views/donations/index.html.slim
app/views/layouts/_navbar.html.slim
app/views/reports/_report_chart.html.slim
app/views/reports/index.html.slim
config/routes.rb
db/seeds/donations.rb
spec/models/donation_spec.rb

This change creates a report form which can be accessed by clicking on "Reports" link in the `navbar`. After a User fills in the report form, a chart is generated to visualize the data.
**Note:** This change edits `donation.rb` seed file. Please run `rake db:drop db:create db:migrate db:seed`.
---
Default view:
Donations for chosen year:
Donations for chosen year and month:
Donations for chosen year and cause:
Donations for chosen year, month and cause:
Donations for chosen year and event:
Donations for chosen year, month and event:
---
---
is important, please …

Allow users fill in a report form and see a chart representing requested data

---

config/environments/production.rb

This change fixes (hopefully) the error that appears after a User clicks in a "Change my password" link in the email. 
See the screenshots below.
---
---
---

Fix "Forgot Password" functionality on Heroku

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/helpers/events_helper.rb
app/models/donor.rb
app/models/event.rb
app/views/events/_index.html.slim
app/views/events/show.html.slim
config/locales/en.yml
db/migrate/20161116012055_create_versions.rb
db/schema.rb
spec/models/event_spec.rb
spec/rails_helper.rb

This change adds a date, time and a user's email for when an event was created or updated on `events/show` page. 
**Note:** 
1. This change adds a "paper_trail" gem. Please run `bundle install`.
2. This change contains a migration. Please run `rake:db migrate`.
---
Event was created:
Event was updated:
The event was created before the versioning was turned on:
---
---
[3]: …

Allow Users to see who created or updated an Event and when

---

app/models/cause.rb
app/views/donations/index.html.slim

This change enhances `Cause#top_donation_for_year` to make it dynamic.
---
---

Update Cause#top_donation_for_year to take "date" as a param

---

app/views/events/show.html.slim

This change allows donations to be edited from the events/show page.
Screen shot:
---
---
---

Edit donations on events/show page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/donations/index.html.slim
app/views/donors/index.html.slim
app/views/events/_index.html.slim
app/views/events/show.html.slim
app/views/layouts/_navbar.html.slim
app/views/layouts/application.html.slim
app/views/sessions/new.html.slim

This change adds/updates the Bootstrap classes to make the app fully responsive, including the `navbar`.
Note: this change edits the Gemfile. Please run `bundle install`.
---
---
---

Allow users to easily use the app on mobile devices

---

app/controllers/clearance/passwords_controller.rb
app/controllers/clearance/users_controller.rb
app/views/donations/_form.html.slim
app/views/users/_form.html.slim
app/views/users/_new.html.slim
app/views/users/create.js.erb
app/views/users/show.html.slim
config/initializers/clearance.rb
config/routes.rb

This change allows a logged in user to create a new user account on the users#show page.
Screen shots:
---
---
---

Allow user to create new user account on show page

---

app/assets/javascripts/application.js
app/views/events/index.html.slim
app/views/events/index.js.erb

This change implements ajax pagination on the events/index page.
---
---

[Fix #116] Fix pagination with ajax request on events/index

---

app/controllers/reports_controller.rb
app/finders/donations_reports_finder.rb

This change adds permitted params for reports in `ReportsController` and also handles the case when a month param is passed without a year.
---
---

[Fix #121] Allow Users to enter only whitelisted params to reports

---

app/controllers/passwords_controller.rb
app/views/layouts/_navbar.html.slim
app/views/passwords/custom_edit.html.slim
app/views/sessions/new.html.slim
app/views/users/show.html.slim
config/routes.rb

This change allows a logged-in user to change his password. The link is in the drop-down list on the navbar.
Screenshot:
---
---
---

Allow logged-in user to change password

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/donations_controller.rb
app/controllers/donors_controller.rb
app/helpers/application_helper.rb
app/helpers/events_helper.rb
app/models/donor.rb
app/views/donations/_edit.html.slim
app/views/donations/index.html.slim
app/views/donors/_edit.html.slim
app/views/donors/_show.html.slim
app/views/donors/index.html.slim
app/views/donors/show.html.slim
app/views/events/_index.html.slim
app/views/events/show.html.slim
app/views/reports/_report_chart.html.slim
app/views/reports/_report_table.html.slim
app/views/reports/index.html.slim
db/migrate/20160926083804_create_donors.rb
db/schema.rb
spec/controllers/donations_controller_spec.rb

This change improves the flow of updating a `Donor` on `donors/show`:
- A User sees `donors/edit` form on `donors/show` after he/she created a new `Donation`;
- A User can add :title, :postal_code and :comments for a `Donor`.
**Note:** This change updates the `schema`. Please run `rake db:drop db:create db:migrate db:seed`.
---
---
---
[3]: …

Enhance User experience when updating Donor's information

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/bootstrap-override.scss
app/assets/stylesheets/media-queries.scss
app/assets/stylesheets/modules/buttons.scss
app/assets/stylesheets/modules/cards.scss
app/assets/stylesheets/modules/forms.scss
app/assets/stylesheets/modules/metadata.scss
app/assets/stylesheets/modules/navbar.scss
app/assets/stylesheets/modules/tables.scss
app/views/donations/index.html.slim
app/views/events/index.html.slim
app/views/layouts/_navbar.html.slim

This change adds multiple CSS rules to various elements so that the App visually resembles [http://www.hcsa.org.sg/](http://www.hcsa.org.sg/).
See the screenshots below.
**Note:** 
There are some colour variables added and not used at the moment. These colours are cause-specific. As soon as we get a confirmation from the client about the list of causes, we will proceed with styling cause-specific content.
---
---
---
[2]: …

Add styling to resemble HCSA website

---

app/controllers/clearance/users_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/welcome_email.html.slim

This change allows a new user to receive a welcome email automatically when added to the database.
---
---

Allow new user to receive welcome email 

---

app/controllers/donors_controller.rb
app/controllers/events_controller.rb
app/views/donors/show.html.slim
spec/controllers/donors_controller_spec.rb

This change adds pagination to the donors/show page.
---

Allow pagination on donors/show page

---

app/models/donation.rb
db/migrate/20160926083857_create_donations.rb
db/schema.rb
spec/models/donation_spec.rb

The data we received tracks the payment type. Adding it in to the database, so we don't lose the data.
---
---

Add payment type to donation
