TechLadies/highpoint

app/controllers/donors_controller.rb, app/models/donor.rb, app/views/donors/index.html.erb, app/views/layouts/_navbar.html.erb, config/routes.rb, spec/factories/donors.rb, spec/models/donor_spec.rb
This change creates an `index` page for Donors with a table showing Donor's name, identification and total amount donated.
The `index` page can viewed by pressing "Donors" link in the navigation bar.
See screenshots below:
---
---
---
=> Allow users to see a list of donors

app/controllers/events_controller.rb, app/models/donation.rb, app/models/event.rb, app/views/donations/_new.html.erb, app/views/events/_new.html.erb, app/views/events/index.html.erb, app/views/layouts/_navbar.html.erb, config/routes.rb, db/migrate/20161002134530_create_events.rb, db/schema.rb, db/seeds.rb, db/seeds/events.rb, spec/controllers/events_controller_spec.rb, spec/factories/events.rb, spec/models/event_spec.rb
This change allows users to enter new events through a modal.
Note! This change has migrations. Please run: rake db:drop db:create db:migrate db:seed after pulling the changes.
See screenshots below:
---
---
---
=> Allow Users to create events

app/views/donors/show.html.erb
This change allows users to view a list of donations on the donor page.
The screen shots of the donor page are below.
Screenshot of donor page:
Screenshot when edit form is clicked:
---
---
---
=> Add list of donations to donor page

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
According to the Bootstrap Gem [documentation](https://github.com/twbs/bootstrap-rubygem#a-ruby-on-rails), tooltips depend on another library called Tether. Adding this will hopefully get Bootstrap working on Heroku.
---
---
=> Get Bootstrap 4 working on Heroku

app/views/donations/_new.html.erb, app/views/donors/_edit.html.erb, app/views/donors/_show.html.erb, app/views/donors/index.html.erb
[Fix #19] This change fixes the typo in `donor` and `donation` views from UEM to UEN. In our database the field is called "identification", no change needed there.
---
If you do not know what makes a good commit message, or why it
=> Change references of UEM to UEN for donors and donations

app/controllers/donations_controller.rb, app/models/cause.rb, app/views/donations/_edit.html.erb, app/views/donations/_new.html.erb, app/views/donors/show.html.erb, config/routes.rb, db/migrate/20161009153659_add_event_to_donations.rb, db/schema.rb, db/seeds/donations.rb
This change allows user to edit donations on the donor page. A user can edit both cause and event when editing a donation.
Screenshot of donor page:
Screenshot of donation edit form:
---
---
---
=> Allow user to edit donations on donor page

app/controllers/donations_controller.rb, app/controllers/events_controller.rb, app/models/event.rb, spec/models/event_spec.rb
This change checks that when creating an event `end_on` date cannot be before a `start_on` date.
---
---
=> [Fix #23] Show an error when creating an event with an end date after a start date

app/controllers/events_controller.rb, app/models/donation.rb, app/views/events/show.html.erb, db/seeds/donations.rb, db/seeds/donors.rb, spec/models/donation_spec.rb
This change allows users to search for a donation by entering an donor's name (or a part of it) into a search field on `events/show` page.
It also adds following missing elements on `events/show`:
- Total Amount Donated during the event
- Backlink to `events/index`
**Note:** this change contains updated `seed` files. Please run rake db:drop db:create db:migrate db:seed.
---
---
---
[2]: …
=> Allow users to search for a donation by donor name when viewing an event

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/views/events/_new.html.erb
This change adds a "boostrap-datepicker" gem and lets a user pick a date using an interactive calendar.
**Note:** This change adds a gem, please run `bundle install'.
---
See screenshot below:
---
---
---
- Install "bootstra-datepicker" gem
- Initialize datepicker and add it to events modal
=> [Fix #13] Add datepicker options to event modal

app/controllers/events_controller.rb, app/views/events/show.html.erb, spec/controllers/events_controller_spec.rb
This change updates the `show` action for `Event` to show only `donations` related to that particular event.
---
---
=> [Fix #30] Show only donation related to an event when viewing events

app/controllers/donors_controller.rb, app/models/donor.rb, app/views/donors/index.html.erb, spec/models/donor_spec.rb
This change allows users to search for donors by entering a `donor` name (or a part of it) into a search field on `donors/index` page.
Also this change lets users see the total amount of `Donors` in the system.
---
---
---
=> Allow users to search for a donor on donors/index

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/donations_controller.rb, app/models/donation.rb, app/views/donations/_new.html.erb, app/views/donors/index.html.erb
This change allows a user to choose both cause and event when creating a donation.
Screenshot of form:
---
---
---
=> Allow user to choose both cause and event when creating donation

app/views/donors/index.html.erb, app/views/events/index.html.erb, app/views/events/show.html.erb
There was an issue with the Bootstrap grid, caused by the search row not being wrapped in a container. This change fixes that in all three places:
It also solves some small problems, like indentation issues and typos.
---
---
---
=> [Fix #41] Remove horizontal scrollbars from tables

.rubocop.yml, app/controllers/donations_controller.rb, app/models/donation.rb, app/models/donor.rb, db/migrate/20160926083804_create_donors.rb, db/schema.rb, db/seeds/donations.rb, spec/factories/donors.rb, spec/factories/users.rb, spec/models/donation_spec.rb, spec/models/donor_spec.rb
This change forces `Donor#identification` to be unique both at the application- and database level, since only one person or organization can have the unique identification.
That fixes the issue where creating a donation from the quick donation modal would create a duplicate donor for the donation instead of it being attributed to the existing donor.
It also improves the seeds, so that there's now one donor with no donations, one with one donation, and one with several.
---
---
---
[1]: …
=> [Fix #42] Prevent duplicate donors from being created when adding donations

app/assets/stylesheets/application.scss
This change add CSS that removes small space between `input-field` and `button` in `input-group`.
It is a known issue (https://github.com/twbs/bootstrap/issues/20404), so the CSS added is a work-around until the issue is fixed by Bootstrap.
---
---
---
---
=> [Fix #44] Fix gap issue in .input-group between input-field and button

app/views/donations/_new.html.erb, db/seeds/donors.rb
This change allows users to create a donation with an anonymous donor.
An anonymous donor is added to the seed file.
Screenshot of the form:
---
---
---
=> Allow user to create donation with anonymous donor

app/views/donors/show.html.erb, config/locales/en.yml
This change improves the date formatting on `donor/show` page. The year is shown only of the `donation` was made not during the current year. 
---
---
---
=> [Fix #36] Improve date format of donations on the donor show page

app/controllers/donations_controller.rb, app/models/donation.rb, app/views/donations/_edit.html.erb, app/views/donations/_form.html.erb, app/views/donations/_new.html.erb, app/views/donations/edit.js.erb, app/views/donors/edit.js.erb, app/views/donors/show.html.erb, app/views/events/_new.html.erb, app/views/layouts/_navbar.html.erb, db/seeds/donations.rb, spec/controllers/donations_controller_spec.rb, spec/routing/donations_routing_spec.rb
This change allows a User to edit `donations` on `donors/show` page in a modal.
**Note:** This change contains edited seed files. Please run `rake db:drop db:create db:migrate db:seed`
This change also:
- Sets a default order when showing `donations`
- Has minor edits to the `navbar` layout
---
See screenshots below:
---
---
=> [Fix #40] Allow user edit Donations for Donor

app/controllers/donors_controller.rb, app/models/donor.rb, app/views/donors/index.html.erb, app/views/donors/show.html.erb, db/seeds/causes.rb, spec/factories/causes.rb, spec/factories/donations.rb, spec/factories/donors.rb, spec/models/donor_spec.rb
This change allows a user to filter donors by cause on the donors index page. The total donation amount will also pertain only to filtered donations.
Screenshot of donors index page:
---
---
---
=> Allow user to filter donors by cause on donors index page

app/views/sessions/_form.html.erb, app/views/sessions/new.html.erb, app/views/users/_form.html.erb, spec/models/donor_spec.rb
This change adds some Bootstrap classes to the sign in page, which will serve as a basis for styling it later on.
---
---
---
=> Add rudimentary styling to user sign in page

app/assets/javascripts/application.js
This gem would load all its locales, resulting in a lot of unneeded files being loaded.
This change fixes that, and loads only English.
---
---
=> Prevent `bootstrap-datepicker` from loading all locales

app/assets/javascripts/application.js, app/controllers/donations_controller.rb, app/views/donations/_edit.html.erb, spec/controllers/donations_controller_spec.rb
This change allows Users to edit `created_at` attribute for `Donation`.
See screenshots below:
It also fixes an issue of datepicker working only when the page is reloaded.
---
---
---
- Add "Donated On" form field
- Allow "created_at" attr on Donation
- Make Datepicker work with turbolinks
- Add test for editing Donation's …
=> [Fix #48][Fix #49] Allow Users edit "created_at" for donation

app/views/donors/index.html.erb
This change makes the filter value stick in the select box after filtering `Donors` by `Cause` on `donors/index` page.
---
---
--- 
---
=> [Fix #55] Allow Users to see the filter value in the select box after filtering Donors by Cause on donors/index page

app/controllers/donations_controller.rb, app/models/donation.rb, app/views/donations/index.html.slim, app/views/layouts/_navbar.html.slim, config/routes.rb, spec/factories/donations.rb, spec/factories/donors.rb, spec/models/donation_spec.rb, spec/models/donor_spec.rb, spec/routing/donations_routing_spec.rb
This change creates a Dashboard page which can be accessed by clicking on "HCSA Admin" link in the `navbar`. It also lets Users see the total amount donated for the current year.
---
---
---
- Add link on navbar to dashboard
- Route dashboard to donations/index
- Create donations_for_current_year for …
=> Allow Users to see total donations for current year on the Dashboard page

app/views/donors/show.html.slim
Allow user to link to event from donor/show page
Screenshot:
---
---
---
=> [Fix #67] Add link to event from donor/show page

app/controllers/events_controller.rb, app/views/donations/_new.html.slim, app/views/events/_edit.html.slim, app/views/events/_form.html.slim, app/views/events/_index.html.slim, app/views/events/_new.html.slim, app/views/events/edit.js.erb, app/views/events/update.js.erb, config/routes.rb
This change allows Users to edit an event on `events/index` page by clicking on a "pencil" icon.
This change also:
- [Fix #65] Changes date display format on `events/index`
- Adds notifications to `events/edit` modal if invalid input is entered
---
---
---
---
=> Allow users to edit events

app/assets/javascripts/application.js, app/views/donations/_form.html.slim, app/views/donors/show.html.slim, db/seeds/causes.rb
This change makes several improvements:
- [Fix #71] Makes "General" cause a default option when creating a `donation` ;
- [Fix #72] Lets a User create a `donation` with no `event` associated;
- [Fix #73] Hides error messages from modals after a modal is closed.
**Note:** This change updated the `seed.rb` file. Please run `rake db:drop db:create db:migrate db:seed`.
---
---
---
---
[2]: …
=> Improve modals' UX

app/assets/javascripts/index.js, app/controllers/donors_controller.rb, app/models/cause.rb, app/views/donors/index.html.slim
This change allows a user to sort donors in the donors/show page by total donation amount.
- It allows sorting within the cause and search fields selected.
- It also enables searching within the cause field selected.
Screenshot of donors/show page:
---
---
is important, please refer to these resources: [1](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message), [2](http://chris.beams.io/posts/git-commit/), [3](https://github.com/blog/1943-how-to-write-the-perfect-pull-request).
=> Allow user to sort donors in donors/show page

app/controllers/events_controller.rb, app/models/event.rb, app/views/events/_index.html.slim
This change allows a user to sort events on the events/index by total donations or date of event. 
Note: Rubocop does not pass because of a bloated controller. This can be fixed by creating a Ruby object.
Screenshot:
---
---
=> Allow user to sort events on events/index

app/controllers/donations_controller.rb, app/controllers/events_controller.rb, app/models/donation.rb, app/views/donations/_edit.html.slim, app/views/donations/_form.html.slim, app/views/donations/_new.html.slim, app/views/donations/create.js.erb, app/views/donations/update.js.erb, app/views/donors/show.html.slim, app/views/layouts/application.html.slim
This change fixes issue #66: There are no alerts displayed in the donations modal when creating or editing a Donation.
Screenshot of creating a donation:
Screenshot of editing a donation:
---
---
=> [Fix #66] Display alerts when creating or editing a Donation

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/models/donation.rb, app/views/donations/index.html.slim, db/seeds/causes.rb, db/seeds/donations.rb, spec/controllers/events_controller_spec.rb
This change adds a Digram showing Donations per cause for current year on "Dashboard" page.
**Note:** This change updated seed files and Gemfile. Please run `rake db:drop db:create db:migrate db:seed` and `bundle install`.
---
---
---
=> Add a diagram showing donations per cause to Dashboard page

app/assets/stylesheets/application.scss, app/controllers/donations_controller.rb, app/models/cause.rb, app/views/donations/index.html.slim, app/views/donors/show.html.slim, spec/models/cause_spec.rb
This change adds Topd Donors per `cause` to `donations#index` page.
---
---
---
Fix event link on "donors#show" page
Add CSS styling
=> Allow Users to see Top Donors per Cause on Dashboard page

app/helpers/application_helper.rb, app/views/donors/index.html.slim, app/views/events/_index.html.slim
This change edits the column filters in the donor#index and event#index views so that it is easier to see what filters are on/off. It also adds filters to the name and NRIC/UEN columns of the donor#index view.
However, there is a rubocop offense that the method "sortable" has too many lines.
Screen shot of donor#index view:
Screen shot of event#index view:
---
---
---
[3]: …
=> [Fix #79] Edit column filters

app/assets/stylesheets/application.scss, app/helpers/application_helper.rb
This change adds some CSS to style the sorting icons in tables. 
---
---
---
=> [Fix#86] Add CSS styling to sorting icons

app/controllers/clearance/passwords_controller.rb
This change fixes an error "column users.normalized_email does not exist" by updating `PasswordsController#find_user_for_create`.
---
---
=> Fix an error "column users.normalized_email does not exist"

config/environments/production.rb
This change edits `production.rb` to work with `SendGrid` on Heroku.
@Drenmi could you please check that those variables were created?
```
heroku config:get SENDGRID_USERNAME
appXYZ@heroku.com
$ heroku config:get SENDGRID_PASSWORD
password
```
If they were, this change might fix the error we currently have. 
---
---
=> [Fix #93] Use username and password instead of an API key for SendGrid

app/controllers/events_controller.rb, app/finders/donations_finder.rb, app/helpers/application_helper.rb, app/models/event.rb, app/views/events/show.html.slim, spec/controllers/events_controller_spec.rb
This change allows a user to filter donors and their donations in the events/show page.
Screen shot:
---
---
---
=> Allow user to filter donors in events/show page

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/donors_controller.rb, app/models/donor.rb, app/views/donors/index.html.slim
This change adds pagination to the donors index page so that there is a maximum of 15 donors per page.
Screen shot of the page links:
---
---
=> Add pagination to donors index page

app/controllers/donors_controller.rb, app/controllers/events_controller.rb, app/models/donation.rb, app/models/event.rb, app/views/events/_index.html.slim, app/views/events/show.html.slim, config/application.rb
This change adds pagination to the events/index and events/show pages so that there are a maximum of 15 entries per page.
Update: The pull request has been updated to allow pagination on arrays.
---
---
---
---
=> [Fix #108] Add pagination to events/index and events/show pages

app/models/donation.rb, app/views/donors/index.html.slim, app/views/events/_index.html.slim, app/views/events/show.html.slim, app/views/reports/_report_chart.html.slim, app/views/reports/_report_table.html.slim, app/views/reports/index.html.slim
This change adds a table of donations on `reports/index` page that show donations for a report.
---
---
---
Add “Total Donations” field to reports
=> Allow Users to see a donations' table on reports/index page

app/views/donors/index.html.slim, app/views/events/_index.html.slim, app/views/events/show.html.slim
This change fixes sorting label's display for table headers.
Before:
After:
---
---
---
=> Fix table headers

app/controllers/events_controller.rb
This change fixes a bug that pagination causes the redirect to fail when a new event is saved.
---
---
=> [Fix #113] Fix bug that pagination causes redirect to fail when new event is saved

app/assets/javascripts/application.js, app/views/reports/index.html.slim
This change adds JS to disable a "month" field in report form on `reports/index` page if no "year" is chosen.
---
---
---
=> Disable "month" field in reports form if no year is chosen 

app/controllers/donations_controller.rb, app/views/donors/show.html.slim
This change prompts a user to enter the details of the donor after creating a donation and getting redirected to the "donors/show" page, if the donor was not already in the database.
Screen shot of donors/show view if donor is a new record:
---
---
---
=> Prompt user to enter donor details when donation is created 

spec/finders/donations_finder_spec.rb, spec/finders/donations_reports_finder_spec.rb
This change creates ```donations_finder_spec.rb``` to test the donations finder.
Note: It also renames the original ```donations_finder_spec.rb``` file to ```donations_reports_finder_spec.rb```.
---
---
=> Create donations finder spec

app/views/reports/_report_chart.html.slim
This change allows users to see a month's name instead of a number on `reports/index` after a report is generated.
---
---
---
=> [Fix #94] Allow Users to see a month's name on reports/index after a report is generated.

app/helpers/application_helper.rb, app/helpers/events_helper.rb, app/models/donation.rb, app/views/donations/_edit.html.slim, app/views/donors/show.html.slim, app/views/events/show.html.slim
This change allows Users to see who and when created/update Donor on `donors/show` page and also who and when created/updated a Donation in `donations/edit` modal.
---
---
---
=> Allow Users to see who created/updated a Donor or Donation

app/assets/javascripts/application.js, app/finders/donations_reports_finder.rb, app/views/events/show.html.slim, app/views/reports/_report_table.html.slim, app/views/reports/index.html.slim
This change adds a "Generate Report" button to `events/show` page, after pressing which a User gets redirected to `donations/reports` page with the events name prepopulated in the form.
_P.s. the changes in `ReportsHelper` are made only for test purposes, as this file will be removed from the project in another PR._
---
---
---
[3]: …
=> Allow Users generate a report for a particular event

app/controllers/clearance/passwords_controller.rb
This change fixes the syntax of #find_by_normalized_email in `PasswordsController`.
---
---
=> Fix #find_by_normalized_email

app/assets/javascripts/application.js, app/views/reports/index.html.slim
This change disables a month field in a report's form on `reports/index` when the page is loaded.
Also in the scenario when a year number is chosen, a month is chosen and then a year is switched back to "All" again, the month field is switched to "All" and is disabled.
---
---
---
Also show month as …
=> [Fix #129] Disable a month field initially in report's form

app/controllers/application_controller.rb, app/controllers/donations_controller.rb
This change fixes the bug that flash message after donation is updated is not green.
Before:
After:
---
---
---
=> [Fix #128] Fix alert after donation is updated

app/assets/javascripts/application.js, app/views/donations/_new.html.slim
This change add an "Anonymous" checkbox to a `donations/new` form. When clicked, it pre populates a `Donor`s identification field with "Anonymous". 
---
---
---
=> Let a User check 'Anonymous' option when creating a donation

app/controllers/donors_controller.rb, app/models/donor.rb, app/views/donors/index.html.slim, config/application.rb, config/locales/en.yml
This change adds an "Export" button to `donors/index`, by pressing which a User can download a .csv file with the data from the table.
---
---
---
=> Allow Users to export `donors/index` table data in .csv

app/controllers/events_controller.rb, app/finders/events_finder.rb
This change changes the default ordering of events index from `start_on` to `updated_at` so that when an event is newly created or updated, it will appear at the top of the index.
It also fixes a current error that the modal does not close when an event is updated.
---
---
=> [Fix #95] Change default ordering of events index

app/controllers/application_controller.rb, app/controllers/clearance/users_controller.rb, app/controllers/users_controller.rb, app/views/layouts/_navbar.html.slim, app/views/users/index.html.slim, app/views/users/show.html.slim, config/routes.rb, db/migrate/20161128144810_add_admin_to_users.rb, db/schema.rb, db/seeds/users.rb
This change creates a users/index page that only admin users are able to access. On the users/index page, admin users are able to add a new user or delete existing users.
Note: An admin column has been added to the users table. Run `rake db:migrate` to migrate. The seed file is also updated so that `dawn@highpoint.com` is an admin.
Screenshot:
---
---
---
---
[2]: …
=> Allow only admins to add and delete users

app/controllers/donors_controller.rb, app/controllers/events_controller.rb, app/models/donor.rb, app/views/donors/index.html.slim, app/views/events/_index.html.slim, app/views/events/show.html.slim
This change allows a user to see and reset the search term on the donors/index, events/index and events/show pages.
It also sets a donor's name to `""` on creation, to avoid nil results not showing up when the search value is `nil`.
See screenshots below.
Donors/index:
Events/index:
Events/show:
---
---
---
=> Allow user to see and reset search term

app/models/donor.rb, app/views/donors/_show.html.slim, spec/factories/donors.rb, spec/models/donor_spec.rb
This change adds "Shares address with" information on `donors/show` page.
---
when sharing a postal code with ONE donor:
when sharing a postal code with MULTIPLE donors:
---
---
=> Allow Users to see which Donors share the same postal code

.rubocop.yml, app/controllers/clearance/passwords_controller.rb, app/controllers/donors_controller.rb
This change fixes some RuboCop warnings, and excludes the Clearance controllers form inspection by the Metrics cops, since they have quite a few violations.
---
---
=> Fix RuboCop warnings and tweak configuration

app/helpers/application_helper.rb, app/views/layouts/_navbar.html.slim
This change allows users to see which page is currently opened by changing the color of the link in the `navbar` accordingly.
---
---
---
=> [FIx #144] Show User in navbar which page is currently open

app/views/donations/_edit.html.slim, app/views/donations/_form.html.slim, app/views/donations/_new.html.slim
This change sets submit button's text in `donations/new` modal to "Create Donation" instead of "Save changes".
See the screenshot below
---
---
---
=> Change submit button's text in donations/new modal to "Create Donation"

app/models/donor.rb, app/views/donors/_show.html.slim
This change removes from the equation not only empty postal codes but also the ones that are `nil`.
---
---
=> Allow Users to see which donors share the same postal code only if the donor's postal codes are present

app/models/donor.rb, app/views/donors/_anonymous.html.slim, app/views/donors/show.html.slim
This change removes all unnecessary information about Anonymous donor and renders `donors/anonymous` when new anonymous donation is created.
---
---
---
=> Don't allow Users edit Anonymous donor's information
